[build-system]
requires = [
  "setuptools>=77.0.3",
  "wheel",
  "numpy"
]
build-backend = "setuptools.build_meta"
[project]
name = "classtrees"
version = "1.1.1"
requires-python = ">=3.10"
dependencies = [
  "numpy",
]
authors = [
  {name = "Jakub Sawicki"}
]
description = "Python package implementing classification trees."
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE", "THIRD_PARTY_LICENSES.txt"]
keywords = ["tree", "classification", "samples", "machine learning"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
[project.urls]
Homepage = "https://github.com/kubek22/classtrees"
Documentation = "https://kubek22.github.io/classtrees/"
Repository = "https://github.com/kubek22/classtrees"
[project.optional-dependencies]
test = [
    "pytest",
    "pytest-timeout",
    "numpy",
    "scikit-learn",
]
[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
classtrees = ["*.h"]

[tool.cibuildwheel]
build = "cp310-* cp311-* cp312-*"
skip = "cp310-win32 cp311-win32 cp312-win32"

[tool.cibuildwheel.linux]
before-all = "yum install -y openmp || true"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
